.TH "Really Slick ScreenSavers" 1 "" "X Version 11"
.de Ds
.Sp
.nf
..
.de De
.fi
..
.SH NAME
cyclone - tornado screen saver.
.SH SYNOPSIS
.B cyclone
[\--root/-r]
[\--maxfps/-x \fInumber\fP]
[\--vsync/-y \fInumber\fP]
[\--dpms/-M \fInumber\fP]
[\--cyclones/-c \fInumber\fP]
[\--particles/-p \fInumber\fP]
[\--size/-i \fInumber\fP]
[\--complexity/-C \fInumber\fP]
[\--speed/-e \fInumber\fP]
[\--stretch/-s]
[\--no-stretch/-S]
[\--showcurves/-v]
[\--no-showcurves/-V]
.SH DESCRIPTION
From Terry Walsh (\fIhttp://reallyslick.com\fP):
"This screen saver makes tornadoes on your screen. I wrote it for my storm chasing partner, but you can have it too."

Ported to Linux by Tugrul Galatali.
.SH OPTIONS
.TP 8
.B \--root
Draw on the root window.
.TP 8
.B \--maxfps \fInumber\fP
Set maximum frame rate.
.TP 8
.B \--vsync \fInumber\fP
Limit redraws to specified number of vertical refreshes.  0 - 100.  Default: 1
.TP 8
.B \--dpms \fInumber\fP
Stop rendering new frames if the display is not on.  0 - 1.  Default: 1
.TP 8
.B \--cyclones \fInumber\fP
Number of cyclones.  1 - 10.  Default: 1
.TP 8
.B \--particles \fInumber\fP
Particles per cyclone.  1 - 10000.  Default: 200
.TP 8
.B \--size \fInumber\fP
Particle size.  1 - 100.  Default: 7
.TP 8
.B \--complexity \fInumber\fP
Cyclone complexity.  1 - 10.  Default: 3
.TP 8
.B \--speed \fInumber\fP
Speed.  1 - 100.  Default: 10
.TP 8
.B \--stretch
Stretch.  Default: True
.TP 8
.B \--showcurves
Show Curves.  Default: False
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
to get the default host and display number.
.SH SEE ALSO
.BR X (1),
.SH COPYRIGHT
Copyright \(co 2002 by Terry Walsh and Tugrul Galatali.  

Cyclone is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License version 2 as
published by the Free Software Foundation.

Cyclone is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.SH AUTHOR
Terry Walsh and Tugrul Galatali <tugrul@galatali.com>

